pinojs/sonic-boom

README.md
bench.js
index.js
package.json
test.js

cc @jsumners @davidmarkclements

Simplified code and added minLength parameter

---

README.md
index.js
test.js

Implemented file reopening for log rotation

---

.gitignore
README.md
index.js
test.js

Remove bottleneck in sync mode writing

---

index.js
test.js

Fixes https://github.com/pinojs/pino/issues/710

Fix EBADF in case of a reopen() while an open was in progress.

---

.github/workflows/nodejs.yml
.travis.yml
README.md

Changed from Travis to GitHub Action
** The badge may be broken until the completion of the first run **

GitHub action

---

README.md
example.js
fixtures/firehose.js
index.js
test.js

Ref: https://github.com/pinojs/pino/issues/785
This is a semver-major / breaking change

Use an option object instead of positional arguments

---

.github/workflows/nodejs.yml
index.js
test.js

flushSync could have EAGAIN as much as normal writes

---

index.js
test.js

keep sonic-boom writable while write or open throws

---

.github/workflows/nodejs.yml
index.js

So long, and thanks for all the fish `flatstr`.
(This is a semver-major PR)

Drop flatstr

---

index.js
test.js

Fixes: https://github.com/pinojs/sonic-boom/issues/99

fix: writing deadlock

---

index.js
test.js

Throws error if minLengh >= MAX_WRITE

---

index.js
test.js

Fixes https://github.com/pinojs/pino/issues/1242
Fixes https://github.com/pinojs/pino/issues/1241

Do not close fd 1 and fd 2

---

index.js
test.js

The current logic looks wrong. I don't know exactly what kind of behaviour it would cause but I believe this version is more correct.

fix: max write buffering

---

index.js
test.js

This seems a good idea to do given how the current mechanism work in v2.

Lower MAX_WRITE to 64KB

---

README.md
index.js
test.js
types/index.d.ts
types/index.test-d.ts

feat: add config for mode on file creation

---

.github/workflows/nodejs.yml

ci: bump github actions; reduce job permissions to minimum

---

types/index.test-d.ts

Every other line in this file has an explicit semicolon.
This will stop all of the static analysis tools from crying about it.

style(types/index.test-d.ts): explicitly declare semicolon

---

README.md
index.js
test.js
types/index.d.ts
types/index.test-d.ts

Signed-off-by: Matteo Collina <hello@matteocollina.com>
Ref: https://github.com/pinojs/pino/issues/1497

Added fsync option to flush on write

---

index.js
test.js

Signed-off-by: Matteo Collina <hello@matteocollina.com>
Ref: https://github.com/pinojs/pino/issues/1497
Ref: https://github.com/pinojs/sonic-boom/issues/139

Partial fix for multi-byte characters

---

types/index.test-d.ts

Remove unused variable assignments

test(types): remove unused variable assignments

---

index.js
test.js

fix(flushSync): ensure proper handling of partial sync writes

---

index.js

Apparently a few tests are failing due to this.

Call fsync on close

---

.borp.yaml
package.json

This pr enables borp to move to node test

chore: add borp to move to node:test

---

test/sync.test.js

This PR moves `sync.test.js` to node test

test: move sync.test.js to node test

---

test/mode.test.js

This PR moves `mode.test.js` to node test

test: move mode.test.js to node test

---

test/retry.test.js

This PR moves `retry.test.js` to node test

test: move retry.test.js to node test
