- README.md
- bench.js
- index.js
- test.js
This is mainly to solve https://github.com/pinojs/pino/issues/542, however I found out that it gives us a  20% speed bump when logging things with sync mode in pino benchmarks.
Benchmarks in pino with sonic-boom master:
```
$ node benchmarks/basic.bench.js
benchPino*10000: 162.391ms
benchPinoExtreme*10000: 108.874ms
benchPinoNodeStream*10000: 245.955ms
```
Benchmarks in pino with this PR, enabling sync mode for both destination and extreme:
```
$ node benchmarks/basic.bench.js
benchPino*10000: 147.822ms
benchPinoExtreme*10000: 83.608ms
benchPinoNodeStream*10000: 243.117ms
```
cc @jsumners @davidmarkclements
> Added sync mode

- index.js
- test.js
I noticed that the `finish` event (and the `close` event) isn't being emitted if `end()` is called after `reopen()` and the opening of the new file isn't finished.
This fixes the problem and adds a test case for it.
> Fix finish not being emitted after end() while reopening

- index.js
- test.js
I found another case, similar to the one from #24, where the `finish` event wasn't emitted.
> Fix finish not being emitted

- .travis.yml
- index.js
- package.json
- test.js
Fixes an out-of-memory situation when trying to write a string with length >= 1GB. We are chunking up data with a max of 16 MB, which is plenty for a normal application.
> Fix out of memory

- README.md
- index.js
- test.js
changes file open to `fs.openSync`, when `option.sync === true`
This has implications for the `ready` event - which is no longer relevant for `sync` option, as the file descriptor is ready and the event is fired as part of the instantiation - before it's possible to attach the event listener. 
Fixes pinojs/pino/issues/871
> fs.openSync for option sync:true

- .eslintignore
- .npmignore
- package.json
- tsconfig.json
- types/index.d.ts
- types/index.test-d.ts
refs pinojs/pino#913
refs pinojs/pino#910
> Add TS types

- README.md
- bench.js
- check.js
- example.js
- index.js
- test.js
* Migrates from `var`s to ES6 syntax, sot that there are no more `var`s in the code base
* Also fixes config typo in `check.js`
> Migrate from vars to ES6 syntax

- bench.js
Fixes https://github.com/mcollina/sonic-boom/issues/47
On node v14.5:
```
benchSonic*1000: 505.073ms
benchSonicSync*1000: 9.019s
benchSonic4k*1000: 471.747ms
benchSonicSync4k*1000: 338.145ms
benchCore*1000: 4.228s
benchConsole*1000: 7.986s
benchSonic*1000: 467.774ms
benchSonicSync*1000: 8.954s
benchSonic4k*1000: 463.897ms
benchSonicSync4k*1000: 326.755ms
benchCore*1000: 4.229s
benchConsole*1000: 7.845s
```
On node v14.4:
```
benchSonic*1000: 505.515ms
benchSonicSync*1000: 8.638s
benchSonic4k*1000: 455.108ms
benchSonicSync4k*1000: 326.902ms
benchCore*1000: 5.098s
benchConsole*1000: 7.555s
benchSonic*1000: 445.279ms
benchSonicSync*1000: 8.511s
benchSonic4k*1000: 446.532ms
benchSonicSync4k*1000: 303.18ms
benchCore*1000: 4.589s
benchConsole*1000: 7.377s
```
> remove variability on string generation

- index.js
- test.js
Fixes https://github.com/pinojs/pino/issues/995.
> Do not emit 'error' if we are throwing it with no listeners.

- README.md
- index.js
- test.js
- types/index.d.ts
- types/index.test-d.ts
- append:false opens the file in write mode (i.e., truncate)
- append:true opens the file in append mode (default)
resolves #76
> add append option to control file write mode

- README.md
- index.js
- test.js
- types/index.d.ts
- types/index.test-d.ts
- mkdir:true ensures the directory exists using fs.mkdir with the recursive option
- mkdir:false does not check for the existence of the directory (default)
resolves #78
> add option to ensure directory for dest file exists

- test.js
- if the entry in files is a directory, remove it recursively using rmSync (or rmdirSync in Node 12)
> update teardown step in test suite to properly handle temporary dir

- README.md
- index.js
- test.js
Add a synchronous callback for when we encounter EAGAIN errors. The
function must return `true` or `false` to inform sonic-boom if it should
continue retrying or if it should bubble up the error it encounters.
Fixes: https://github.com/pinojs/sonic-boom/issues/65
---
The implementation here is different than the ones discussed in the issue. Adding a maxEAGAIN/maxFlushRetries prove challeging because of `SonicBoom.release` (hard to keep track of attempts with `SonicBoom.release` and a mix of `fs.write` and `fs.writeSync` in the code). This alternative approach gives control to the user to decide if it should retry or not. With this, flushSync will throw if retryEAGAIN returns false. I'm open to discuss other approaches but wanted to have something as a starting point first.
> Add retryEAGAIN callback function

- .github/dependabot.yml
- .github/workflows/nodejs.yml
See https://github.com/pinojs/pino/pull/1224
> build(dependabot): ignore minor and patch github-actions updates

- index.js
- test.js
Docker has a 16k limit.
Refs: https://github.com/moby/moby/blob/513ec73831269947d38a644c278ce3cac36783b2/daemon/logger/copier.go#L13
Fixes: https://github.com/pinojs/sonic-boom/issues/136
> fix: limit writes to 16k

- README.md
- index.js
- test.js
Hi Pino community!
In order to implement log rotation based on SonicBoom (original [issue](https://github.com/pinojs/pino/issues/1323), I would need a way to track bytes written to the underlying file.
Here is [the PR](https://github.com/feugy/pino-roll/pull/3#discussion_r843753896) for implementing a file rotation transport that can roll either on time or size.
The `write` event exposes this information without compromising performance.
> feat: introduce write event

- README.md
- index.js
- test.js
- types/index.d.ts
- types/index.test-d.ts
Related to https://github.com/pinojs/sonic-boom/issues/138 
I hope I covered everything - please let me know if I need to add/change something.
> feat: add user ability to configure max write #

- package.json
Hooks migrated to `.husky` directory in Husky v6
> chore(package): remove husky object

- .github/workflows/ci.yml
- bench.js
- index.js
- test/retry.test.js
- test/write.test.js
- types/index.d.ts
- types/index.test-d.ts
mashed up quick support for .write(chunk: Buffer), works rather well as long as input is a Buffer, in case it is a utf8 string performance degradation is quite bad. See #173 for why it might be needed
if raw buffer is something that is worth exploring further then I'd be happy to put more effort into having fast paths for both types of encoding, probably by preselecting mode of operation at the time of SonicBoom instantiation
```
benchSonic*1000: 2.189s
benchSonicSync*1000: 8.190s
benchSonic4k*1000: 2.147s
benchSonicSync4k*1000: 1.827s
benchCore*1000: 2.561s
benchConsole*1000: 4.835s
benchSonicBuf*1000: 840.388ms
benchSonicSyncBuf*1000: 6.882s
benchSonic4kBuf*1000: 824.605ms
benchSonicSync4kBuf*1000: 481.976ms
benchCoreBuf*1000: 824.466ms
benchSonic*1000: 2.105s
benchSonicSync*1000: …
```
> .write(Buffer) support

- index.js
- test/flush.test.js
while trying to add a callback function to flush in `pino` I got into a situation where I logged and flushed before the file was ready so the cb never got called
> prevent memory leak when writing before ready

- index.js
- test/write.test.js
Fixes #139
Although https://github.com/pinojs/sonic-boom/issues/139#issuecomment-1195160279 suggested converting `this._writingBuf` to a buffer, I found that it might reduce performance if we convert every `this._writingBuf` which just simply writes string.
Therefore, I only handle cases when multi-byte characters exist.
> Convert writingBuf to Buffer to compute the original string length

- index.js
This should be significantly faster in node 22.7
> perf: convert to buffer during async writes

- README.md
- index.js
- package.json
- test/periodicflush.test.js
- types/index.d.ts
- types/index.test-d.ts
> add periodicFlush option

- README.md
Forgot to update the doc after merging https://github.com/pinojs/sonic-boom/pull/174
> chore(readme): missing doc for contentMode

- .github/workflows/ci.yml
This PR removes node 18 and adds node 22 and 24 to CI
> chore: review node versions in CI

- test/reopen.test.js
This PR moves `reopen.test.js` to node:test
> chore: move reopen.test.js to node:test
